import type { Metadata } from 'next';
import './globals.css';
import AmplitudeContextProvider from '@/Amplitude';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <AmplitudeContextProvider userId="">
          {children}
        </AmplitudeContextProvider>
      </body>
    </html>
  );
}
