import type { Metadata } from 'next';
import './globals.css';
import AmplitudeContextProvider from '@/Amplitude';
import SentryProvider from '@/Sentry';
import MSWProvider from '@/MSWProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <MSWProvider>
          <AmplitudeContextProvider userId="">
            {process.env.NEXT_PUBLIC_NODE_ENV === 'development' ? (
              <> {children}</>
            ) : (
              <SentryProvider>{children}</SentryProvider>
            )}
          </AmplitudeContextProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
